### ISSUE TITLE
plugin is not compatible with QGIS 3.0 and above

### ISSUE THREAD

**Issue by mayeulk** [wondie/batch_gps_importer#4]
The plugin is not compatible with QGIS 3.0 and above.
Any plan to upgrade it? Documentation and discussion on the plugin migration here:
https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3
https://gisforthought.com/updating-a-plugin-from-qgis-2-to-qgis-3/

**Comment by wondie** [comment]
@mayeulk that is true. I will upgrade it in few months time. Thank you for the suggest and useful links!

**Comment by wondie** [comment]
@mayeulk I am almost done with the build but got stuck with [QGIS issue](https://issues.qgis.org/issues/19560). With the exception of the extent groupbox, the rest works. You can download it and test.

**Comment by wondie** [comment]
@mayeulk this issue is now fixed. The plugin that is compatible with with QGIS 3.x is uploaded in QGIS plugins.
