### ISSUE TITLE
Not all values are imported

### ISSUE THREAD

**Issue by arn13** [wondie/batch_gps_importer#5]
Hi.
When I import about 60 gpx files the combined_gpx has some values missing on some of the imported data. So NULL for capture time, elevation, name and symbol. This happens consistently with some files of one set.
greetings
Arn

**Comment by wondie** [comment]
@DrArn sorry for the problem. Which QGIS version are you using? It would be good to have these files as a sample so that I can test and fix the issue.

**Comment by arn13** [comment]
Im on version 3.4.3 om Win 10 and Linux Mint.
I think it also happens with 3.2.something on Win 7.
I will send you the files tomorrow.

**Comment by wondie** [comment]
It has been a while. Were you able to get a solution? If not, could you send me the files so that I try to reproduce the issue?

**Comment by wondie** [comment]
I am closing the issue due to lack of response.

**Comment by jpccarpenter** [comment]
@wondie I'm having the same issue w/ no field values passed to the new imported file. Are you still supporting this plug-in?
